spring:
  application:
    name: api-gateway-service
server:
  port: 9191
management:
  endpoints:
    web:
      exposure:
        include:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
