spring:
  application:
    name: api-gateway-service
server:
  port: 9191
management:
  endpoints:
    web:
      exposure:
        include:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
cloud:
    gateway:
      routes:
        - id: CUSTOMER-SERVICE
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/order/**
        - id: CUSTOMER-SERVICE
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/order/**
