server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/user1db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: AUTH-SERVICE
  config:
    import: configserver:http://${CONFIG_SERVER_URL:localhost}:8888
eureka:
  instance:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
jwt:
  secret: mySecretKey
  expireMs: 120000
  refrEshexpireMs: 120000
