server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/authdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: AUTH-SERVICE
eureka:
  instance:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
management:
  endpoints:
    web:
      exposure:
        include: refresh,health
jwt:
  secret: mySecretKey
  expireMs: 120000
  refrEshexpireMs: 120000
api:
  profile: http://PROFILE-SERVICE/api/profile
