spring: 
  datasource:
      username: root
      password: root@123
      url: jdbc:mysql://localhost:3306/customer
      
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
          
  jackson:
    serialization:
      fail-on-empty-beans: false
      
server:
  port: 9010
  error:
    include-message: always
