spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/profiledb
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  jackson:
    serialization:
      fail-on-empty-beans: false
  application:
    name: profile-service
server:
  port: 0
  error:
    include-message: always
eureka:
  instance:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
management:
  endpoints:
    web:
      exposure:
        include: refresh,health
api:
  user: http://USER-SERVICE/api/user
  experience: http://EXPERIENCE-SERVICE/api/experience
  education: http://EDUCATION-SERVICE/api/education
  auth: http://AUTH-SERVICE/api/user
